# This is a basic workflow to help you get started with Actions

name: Update site
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  triggerJob:    
    runs-on: ubuntu-latest    
    steps:    
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch      
      - name: Workflow Dispatch      
        uses: benc-uk/workflow-dispatch@v1.1
        with:          
          workflow: Generate documentation          
          token: ${{secrets.GH_LABS_TOKEN}}          
          inputs: '{ "branch": ${{steps.extract_branch.outputs.branch}} }'          
          ref: master          
          repo: benjaminParisel/bonitasoft.github.io
